### ISSUE TITLE
Hard coded C-drive points program to look at wrong drive for journal files when user profile is on different drive/partition

### ISSUE THREAD

**Issue by cyberbofh** [breca/elite_bgs_companion#30]
Hey, 

I noticed that the program didn't work for me.
When I enabled 'debug' in the settings, I found out that **the program looks at the C-drive** for \username\Saved Games\Frontier Developments\Elite Dangerous, while MY userprofile is on a different partition

In **BGS Companion.py** , line 90, I found the problem:

`'journal_path': path.join('C:\\Users\\ + environ.get("USERNAME") + '\\Saved Games\\Frontier Developments\\Elite Dangerous'),`

If you use the %username% variable, it will point to the right user profile folder, no matter what partition it is on.

**Comment by breca** [comment]
Ah, yep, rookie mistake. Thanks Cyberbofh.

**Comment by breca** [comment]
Should be fixed in 09f52d9fc1f0e5a9ecc5bd73e97755df271639e8
